version: '3.7'
volumes:
  dynamodb_data:
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    ports:
      - 8000:8000
    volumes:
      - ./volumes/data/dynamo:/home/dynamodblocal/data
  kms-local:
    container_name: kms-local
    image: nsmithuk/local-kms
    volumes:
      - ./config:/init
      - ./volumes/data/secrets:/data
    ports:
      - 8080:8080
  hvault:
    depends_on:
      - dynamodb-local
      - kms-local
    image: vault:latest
    links:
      - "dynamodb-local"
      - "kms-local"
    container_name: hvault
    ports:
      - 8200:8200
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200/'
      AWS_ACCESS_KEY_ID: 'XXXXXXXXXXXXXXXXX'
      AWS_SECRET_ACCESS_KEY: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_KMS_ENDPOINT: 'http://kms-local:8080'
      AWS_DYNAMODB_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_DYNAMODB_TABLE: 'vault-data'
      DYNAMODB_HA_ENABLED: 'false'
      VAULT_AWSKMS_SEAL_KEY_ID: 'bc436485-5092-42b8-92a3-0aa8b93536dc'
      VAULT_SEAL_TYPE: 'awskms'
      SKIP_SETCAP: 'true'
      VAULT_LOCAL_CONFIG: '{"storage":{"dynamodb":{}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}},"ui":true,"disable_mlock":true}'
    command: 'server'
  vault-initiator:
    depends_on:
      - hvault
    container_name: vault-initiator
    links:
      - "dynamodb-local"
      - "kms-local"
      - "hvault"
    volumes:
      - ~/.aws/:/root/.aws:ro
    environment:
      AWS_DEFAULT_REGION: 'us-east-1'
      VAULT_ADDR: 'http://hvault:8200'
      VAULT_FORMAT: 'json'
      VAULT_SECRETS_S: '10'
      VAULT_SECRETS_T: '3'
      VAULT_RECOVERY_S: '10'
      VAULT_RECOVERY_T: '3'
      AWS_SM_RECOVERY_KEYS: 'arn:aws:secretsmanager:us-east-1:951145066533:secret:hvault-recovery-key-HLlvz5'
      AWS_SM_ROOT_TOKEN: 'arn:aws:secretsmanager:us-east-1:951145066533:secret:hvault-root-key-1TbDQc'
    build:
      context: .
      dockerfile: Dockerfile